<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="F_Add" Id="{795e5762-f6ee-4d3d-b93c-a8f107056e8a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Add : INT
VAR_INPUT
		iVAlue : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[iValue := iValue + 10;
F_Add :=  iValue;


(*iNumber remains 5 Because function modified only copy *)]]></ST>
    </Implementation>
    <LineIds Name="F_Add">
      <LineId Id="9" Count="3" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>