<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Add" Id="{c050360c-48e5-4dfb-9ac6-5ec662c8ac86}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Add
VAR_IN_OUT
    iValue : INT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[iValue := iValue + 10;]]></ST>
    </Implementation>
    <LineIds Name="FB_Add">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>