<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_XmlPersistentEventStorage" Id="{0f3984ac-7c24-4fdf-93c5-027661fcd10e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_XmlPersistentEventStorage IMPLEMENTS I_PersistentEventStorage
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="StoreEvent" Id="{acfa180f-3f4a-42fd-bc60-0a3c3f36290c}">
      <Declaration><![CDATA[
METHOD StoreEvent
VAR_INPUT
	stEvent	: ST_Event;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[//  Here is the implementation of this method and XML writing is done to store the event]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_XmlPersistentEventStorage">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_XmlPersistentEventStorage.StoreEvent">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>