<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_IntensiveWatch" Id="{1b624a9a-787a-46df-943d-ffbad20b2ca8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_IntensiveWatch IMPLEMENTS I_WashStrategy
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetWashSettings" Id="{94ac178f-107e-4af5-9eb7-e84316509b2b}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD GetWashSettings
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ProgramName" Id="{994d12cf-fbc6-45d2-883a-a099bfdf27c6}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD ProgramName : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_IntensiveWatch">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_IntensiveWatch.GetWashSettings">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_IntensiveWatch.ProgramName">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>