<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_WashingMachineController" Id="{7fc4a27f-0c32-4ced-8960-689687115f9f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WashingMachineController
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_WashingMachineController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>