<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{9e9a7663-4690-4d06-9cc3-05892feac2e3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	iNumber : INT := 5;
    fbAdd   : FB_Add;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbAdd.SetReference(iNumber);
fbAdd.Execute();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="12" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>