<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{b8d36c91-9156-4abc-ac0a-4ccc8654df5d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
     MyServo    : ServoMotor;
	 MyDigitalMotor: DigitalMotor;
	 
     MyConveyor : Conveyor;
	
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//By using VAR_INPUT DI
//Injecting the dependency (The Servo) into the Conveyor
MyConveyor(itfMotor := MyServo);
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="8" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="15" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>