<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="Account" Id="{ec5a15dd-b1f1-40e0-b446-f833c3745b63}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Account

VAR
        PRIVATE 
             lrBalance : LREAL := 0.0; 
		END_VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Account">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>