<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{718479ac-36c3-4997-8e92-bc04a03d232a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ReadCoil : FB_ReadCoil;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ReadCoil();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>