<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{70310790-146b-4af4-924d-b054ad43cb50}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
   //  MyServo    : ServoMotor;
	 MyDigitalMotor: DigitalMotor;
    
	
	 MyConveyor : Conveyor(itfMotor := MyDigitalMotor);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MyConveyor();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>