<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{6f8315ec-3dc3-4c5b-97a5-90ceec5b20c7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	i:INT:=0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>