<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Parent" Id="{dea553f7-b534-44d6-ad91-d48fab43a13d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Parent
VAR
	sOutput : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Eat" Id="{76cac19c-1079-4b8e-a563-a1eeaac78e54}">
      <Declaration><![CDATA[METHOD ABSTRACT Eat
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{146764ac-048e-4fbc-950b-fbcf7acad751}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[sOutput := 'I am in the parent class';]]></ST>
      </Implementation>
    </Method>
    <Method Name="Greet" Id="{cdde60cd-3ce3-48a0-a000-7926ce0b471b}">
      <Declaration><![CDATA[METHOD ABSTRACT Greet  
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Greeting" Id="{63d452c3-ae38-4372-9d94-47bda443a9ad}">
      <Declaration><![CDATA[METHOD Greeting
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[sOutput := 'Greetings of the day : ';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Parent">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Parent.Eat">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Parent.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_Parent.Greet">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Parent.Greeting">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>