<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{9601e1cc-1db9-453d-bda5-3275aa4ef18b}" SpecialFunc="None">
    <Declaration><![CDATA[// Runtime 2 MAIN — nothing special needed
// just declare a variable
PROGRAM MAIN
VAR
    nMyValue : INT := 99;      // this is what Runtime 1 will read
    rMyTemp  : REAL := 36.5;   // this too
	nWriteValue : INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>