<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Room" Id="{c99913c1-4235-4642-acb7-c51c880677d5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Room

VAR
	 sOutput : STRING := '';
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{2f52d198-f209-4226-8da2-38864d17eea6}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[sOutput := 'Room created inside House';]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Room">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Room.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>