<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="F_CelsiustoFahrenheit" Id="{5615a6d7-436e-418e-a2ca-da110f845913}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_CelsiustoFahrenheit : REAL
VAR_INPUT
		fCelsius : REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_CelsiustoFahrenheit := fCelsius*1.8 + 32.0;]]></ST>
    </Implementation>
    <LineIds Name="F_CelsiustoFahrenheit">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>