<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_Elephant" Id="{1906ab5d-282c-413c-9bd4-0ca0cc8ca2e1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Elephant IMPLEMENTS I_AnimalTraits
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="DietType" Id="{26ada29d-1b1e-4e21-9034-8c86b0578af8}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD DietType : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="IsDangerous" Id="{306f6623-ce47-484b-8c7c-5d9830a4fad6}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD IsDangerous : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="FB_Elephant">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elephant.DietType">
      <LineId Id="4" Count="0" />
    </LineIds>
    <LineIds Name="FB_Elephant.IsDangerous">
      <LineId Id="4" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>