<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="FB_PowerBoost" Id="{a56dad87-fc03-4365-a2d7-efc89c1e2223}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PowerBoost
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	fbPowerBoost: POINTER TO FB_AnimalController;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties>
      <XmlArchive>
        <Data>
          <o xml:space="preserve" t="UMLStereoTypeContainerObject">
            <v n="IsType" t="UMLType">BaseArea</v>
            <v n="Stereotype">""</v>
            <d n="Stereotypes" t="Hashtable" />
          </o>
        </Data>
        <TypeList>
          <Type n="Hashtable">System.Collections.Hashtable</Type>
          <Type n="String">System.String</Type>
          <Type n="UMLStereoTypeContainerObject">{30250973-b110-4e31-b562-c102e042dca4}</Type>
          <Type n="UMLType">{0197b136-405a-42ee-bb27-fd08b621d0cf}</Type>
        </TypeList>
      </XmlArchive>
    </ObjectProperties>
    <LineIds Name="FB_PowerBoost">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>