<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{c1c487e3-3eb3-4b91-9345-a7f6cff229cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	VarFB_Elephant: FB_Elephant;
	VarFB_AnimalController: FB_AnimalController;
	e_SelectedAnimal1: E_SelectedAnimal;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>